name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  Linux:
    name: Linux

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        cxx: [g++, clang++]
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v2
    - name: Before script
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install cppcheck
        $CXX --version
    - name: Script
      run: |
        $CXX -Wall -g -fsanitize=address tables.cpp -o tables
        ./tables
        $CXX -Wall -g -fsanitize=address graphs.cpp -o graphs
        ./graphs
    - name: Cppcheck
      run: cppcheck --enable=all .

